name: Changesets
description: A GitHub action to automate releases with Changesets
runs:
  using: "node12"
  main: "dist/index.js"
inputs:
  publish:
    description: "The command to use to build and publish packages"
    required: false
branding:
  icon: "package"
  color: "blue"
